server:
  port: 8020
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://129.28.201.208:3060/yurt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yurt
    password: 9cbRwItUtxCyy0PR
  jackson:
    default-property-inclusion: non_empty
  mustache:
    suffix: .html
    expose-spring-macro-helpers: false

yurt:
  view:
    ui: element
    cdn-host: http://cdn.skeyurt.net



logging:
  level:
    #    com.github: debug
    org:
      springframework:
        web: trace
        security: trace
        jdbc: debug
        security.access.prepost: info
        boot:
          web.servlet: debug
#        security: debug


